//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tm.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_DoctorOrder
    {
        public int DoctorId { get; set; }
        public long OrderId { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<System.DateTime> DiagnosisDate { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TM_Order TM_Order { get; set; }
        public virtual TM_Users TM_Users { get; set; }
        public virtual TM_Users TM_Users1 { get; set; }
    }
}
