//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tm.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TM_Order()
        {
            this.TM_DoctorOrder = new HashSet<TM_DoctorOrder>();
            this.TM_OrderParam = new HashSet<TM_OrderParam>();
            this.TM_OrderSymptom = new HashSet<TM_OrderSymptom>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Notes { get; set; }
        public string Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TM_DoctorOrder> TM_DoctorOrder { get; set; }
        public virtual TM_Users TM_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TM_OrderParam> TM_OrderParam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TM_OrderSymptom> TM_OrderSymptom { get; set; }
    }
}
