//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tm.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_OrderParam
    {
        public long OrderId { get; set; }
        public short ParamId { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<System.DateTime> MeasureDate { get; set; }
    
        public virtual TM_MeasureParam TM_MeasureParam { get; set; }
        public virtual TM_Order TM_Order { get; set; }
    }
}
