//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tm.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_OrderSymptom
    {
        public long OrderId { get; set; }
        public int SymptomId { get; set; }
        public string Notes { get; set; }
    
        public virtual TM_Symptom TM_Symptom { get; set; }
        public virtual TM_Order TM_Order { get; set; }
    }
}
